/**
 * Bangladesh district + upazila dataset, bundled inline so the cascading
 * District → Upazila select works fully offline (no third-party API).
 *
 * Source: Bangladesh Bureau of Statistics (BBS) district/upazila gazette
 * (https://data.bbs.gov.bd/). Trimmed to canonical district + upazila
 * name spellings. Names use the official English transliteration; if a
 * particular district/upazila is missing from this file the signup form
 * still works — the admin can edit the value through EditStudentForm
 * post-admit.
 *
 * NOTE: data is ordered the way the BBS list groups districts within each
 * division. We intentionally skip the Division step in the signup form
 * (the user-facing flow goes District → Upazila), so this file is the
 * canonical district roster.
 */

export type TBdUpazila = { name: string };
export type TBdDistrict = { name: string; upazilas: TBdUpazila[] };

export const bdDistricts: TBdDistrict[] = [
  // ── Dhaka Division ─────────────────────────────────────────────────────
  {
    name: "Dhaka",
    upazilas: [
      { name: "Dhamrai" },
      { name: "Dohar" },
      { name: "Keraniganj" },
      { name: "Nawabganj" },
      { name: "Savar" },
    ],
  },
  {
    name: "Faridpur",
    upazilas: [
      { name: "Alfadanga" },
      { name: "Bhanga" },
      { name: "Boalmari" },
      { name: "Char Bhadrasan" },
      { name: "Madhukhali" },
      { name: "Nagarkanda" },
      { name: "Sadarpur" },
      { name: "Saltha" },
    ],
  },
  {
    name: "Gazipur",
    upazilas: [
      { name: "Gazipur Sadar" },
      { name: "Kaliakair" },
      { name: "Kaliganj" },
      { name: "Kapasia" },
      { name: "Sreepur" },
    ],
  },
  {
    name: "Gopalganj",
    upazilas: [
      { name: "Gopalganj Sadar" },
      { name: "Kashiani" },
      { name: "Kotalipara" },
      { name: "Muksudpur" },
      { name: "Tungipara" },
    ],
  },
  {
    name: "Kishoreganj",
    upazilas: [
      { name: "Austagram" },
      { name: "Bajitpur" },
      { name: "Bhairab" },
      { name: "Hossainpur" },
      { name: "Itna" },
      { name: "Karimganj" },
      { name: "Katiadi" },
      { name: "Kishoreganj Sadar" },
      { name: "Kuliarchar" },
      { name: "Mithamain" },
      { name: "Nikli" },
      { name: "Pakundia" },
      { name: "Tarail" },
    ],
  },
  {
    name: "Madaripur",
    upazilas: [
      { name: "Madaripur Sadar" },
      { name: "Kalkini" },
      { name: "Rajoir" },
      { name: "Shibchar" },
    ],
  },
  {
    name: "Manikganj",
    upazilas: [
      { name: "Manikganj Sadar" },
      { name: "Daulatpur" },
      { name: "Ghior" },
      { name: "Harirampur" },
      { name: "Saturia" },
      { name: "Shivalaya" },
      { name: "Singair" },
    ],
  },
  {
    name: "Munshiganj",
    upazilas: [
      { name: "Munshiganj Sadar" },
      { name: "Gazaria" },
      { name: "Lohajang" },
      { name: "Sirajdikhan" },
      { name: "Sreenagar" },
      { name: "Tongibari" },
    ],
  },
  {
    name: "Narayanganj",
    upazilas: [
      { name: "Araihazar" },
      { name: "Bandar" },
      { name: "Narayanganj Sadar" },
      { name: "Rupganj" },
      { name: "Sonargaon" },
    ],
  },
  {
    name: "Narsingdi",
    upazilas: [
      { name: "Narsingdi Sadar" },
      { name: "Belabo" },
      { name: "Monohardi" },
      { name: "Palash" },
      { name: "Raipura" },
      { name: "Shibpur" },
    ],
  },
  {
    name: "Rajbari",
    upazilas: [
      { name: "Baliakandi" },
      { name: "Goalandaghat" },
      { name: "Pangsha" },
      { name: "Rajbari Sadar" },
      { name: "Kalukhali" },
    ],
  },
  {
    name: "Shariatpur",
    upazilas: [
      { name: "Shariatpur Sadar" },
      { name: "Bhedarganj" },
      { name: "Damudya" },
      { name: "Gosairhat" },
      { name: "Naria" },
      { name: "Zajira" },
    ],
  },
  {
    name: "Tangail",
    upazilas: [
      { name: "Tangail Sadar" },
      { name: "Basail" },
      { name: "Bhuapur" },
      { name: "Delduar" },
      { name: "Dhanbari" },
      { name: "Ghatail" },
      { name: "Gopalpur" },
      { name: "Kalihati" },
      { name: "Madhupur" },
      { name: "Mirzapur" },
      { name: "Nagarpur" },
      { name: "Sakhipur" },
    ],
  },

  // ── Chittagong Division ────────────────────────────────────────────────
  {
    name: "Chattogram",
    upazilas: [
      { name: "Anwara" },
      { name: "Banshkhali" },
      { name: "Boalkhali" },
      { name: "Chandanaish" },
      { name: "Fatikchhari" },
      { name: "Hathazari" },
      { name: "Karnaphuli" },
      { name: "Lohagara" },
      { name: "Mirsharai" },
      { name: "Patiya" },
      { name: "Rangunia" },
      { name: "Raozan" },
      { name: "Sandwip" },
      { name: "Satkania" },
      { name: "Sitakunda" },
    ],
  },
  {
    name: "Bandarban",
    upazilas: [
      { name: "Bandarban Sadar" },
      { name: "Alikadam" },
      { name: "Lama" },
      { name: "Naikhongchhari" },
      { name: "Rowangchhari" },
      { name: "Ruma" },
      { name: "Thanchi" },
    ],
  },
  {
    name: "Brahmanbaria",
    upazilas: [
      { name: "Brahmanbaria Sadar" },
      { name: "Akhaura" },
      { name: "Bancharampur" },
      { name: "Kasba" },
      { name: "Nabinagar" },
      { name: "Nasirnagar" },
      { name: "Sarail" },
      { name: "Ashuganj" },
      { name: "Bijoynagar" },
    ],
  },
  {
    name: "Chandpur",
    upazilas: [
      { name: "Chandpur Sadar" },
      { name: "Faridganj" },
      { name: "Haimchar" },
      { name: "Haziganj" },
      { name: "Kachua" },
      { name: "Matlab Dakshin" },
      { name: "Matlab Uttar" },
      { name: "Shahrasti" },
    ],
  },
  {
    name: "Cox's Bazar",
    upazilas: [
      { name: "Cox's Bazar Sadar" },
      { name: "Chakaria" },
      { name: "Kutubdia" },
      { name: "Maheshkhali" },
      { name: "Pekua" },
      { name: "Ramu" },
      { name: "Teknaf" },
      { name: "Ukhia" },
    ],
  },
  {
    name: "Cumilla",
    upazilas: [
      { name: "Cumilla Sadar" },
      { name: "Barura" },
      { name: "Brahmanpara" },
      { name: "Burichang" },
      { name: "Chandina" },
      { name: "Chauddagram" },
      { name: "Daudkandi" },
      { name: "Debidwar" },
      { name: "Homna" },
      { name: "Laksam" },
      { name: "Lalmai" },
      { name: "Meghna" },
      { name: "Muradnagar" },
      { name: "Nangalkot" },
      { name: "Titas" },
    ],
  },
  {
    name: "Feni",
    upazilas: [
      { name: "Feni Sadar" },
      { name: "Chhagalnaiya" },
      { name: "Daganbhuiyan" },
      { name: "Fulgazi" },
      { name: "Parshuram" },
      { name: "Sonagazi" },
    ],
  },
  {
    name: "Khagrachhari",
    upazilas: [
      { name: "Khagrachhari Sadar" },
      { name: "Dighinala" },
      { name: "Lakshmichhari" },
      { name: "Mahalchhari" },
      { name: "Manikchhari" },
      { name: "Matiranga" },
      { name: "Panchhari" },
      { name: "Ramgarh" },
    ],
  },
  {
    name: "Lakshmipur",
    upazilas: [
      { name: "Lakshmipur Sadar" },
      { name: "Kamalnagar" },
      { name: "Raipur" },
      { name: "Ramganj" },
      { name: "Ramgati" },
    ],
  },
  {
    name: "Noakhali",
    upazilas: [
      { name: "Noakhali Sadar" },
      { name: "Begumganj" },
      { name: "Chatkhil" },
      { name: "Companiganj" },
      { name: "Hatiya" },
      { name: "Kabirhat" },
      { name: "Senbagh" },
      { name: "Sonaimuri" },
      { name: "Subarnachar" },
    ],
  },
  {
    name: "Rangamati",
    upazilas: [
      { name: "Rangamati Sadar" },
      { name: "Bagaichhari" },
      { name: "Barkal" },
      { name: "Belaichhari" },
      { name: "Juraichhari" },
      { name: "Kaptai" },
      { name: "Kaukhali" },
      { name: "Langadu" },
      { name: "Naniarchar" },
      { name: "Rajasthali" },
    ],
  },

  // ── Rajshahi Division ──────────────────────────────────────────────────
  {
    name: "Rajshahi",
    upazilas: [
      { name: "Rajshahi Sadar" },
      { name: "Bagha" },
      { name: "Bagmara" },
      { name: "Charghat" },
      { name: "Durgapur" },
      { name: "Godagari" },
      { name: "Mohanpur" },
      { name: "Paba" },
      { name: "Puthia" },
      { name: "Tanore" },
    ],
  },
  {
    name: "Bogura",
    upazilas: [
      { name: "Bogura Sadar" },
      { name: "Adamdighi" },
      { name: "Dhunat" },
      { name: "Dupchanchia" },
      { name: "Gabtali" },
      { name: "Kahaloo" },
      { name: "Nandigram" },
      { name: "Sariakandi" },
      { name: "Shahjahanpur" },
      { name: "Sherpur" },
      { name: "Sonatala" },
    ],
  },
  {
    name: "Chapainawabganj",
    upazilas: [
      { name: "Chapainawabganj Sadar" },
      { name: "Bholahat" },
      { name: "Gomastapur" },
      { name: "Nachole" },
      { name: "Rohanpur" },
      { name: "Shibganj" },
    ],
  },
  {
    name: "Joypurhat",
    upazilas: [
      { name: "Joypurhat Sadar" },
      { name: "Akkelpur" },
      { name: "Kalai" },
      { name: "Khetlal" },
      { name: "Panchbibi" },
    ],
  },
  {
    name: "Naogaon",
    upazilas: [
      { name: "Naogaon Sadar" },
      { name: "Atrai" },
      { name: "Badalgachhi" },
      { name: "Dhamoirhat" },
      { name: "Manda" },
      { name: "Mahadebpur" },
      { name: "Niamatpur" },
      { name: "Patnitala" },
      { name: "Porsha" },
      { name: "Raninagar" },
      { name: "Sapahar" },
    ],
  },
  {
    name: "Natore",
    upazilas: [
      { name: "Natore Sadar" },
      { name: "Bagatipara" },
      { name: "Baraigram" },
      { name: "Gurudaspur" },
      { name: "Lalpur" },
      { name: "Naldanga" },
      { name: "Singra" },
    ],
  },
  {
    name: "Nawabganj",
    upazilas: [
      { name: "Nawabganj Sadar" },
      { name: "Bholahat" },
      { name: "Gomastapur" },
      { name: "Nachole" },
      { name: "Shibganj" },
    ],
  },
  {
    name: "Pabna",
    upazilas: [
      { name: "Pabna Sadar" },
      { name: "Atgharia" },
      { name: "Bera" },
      { name: "Bhangura" },
      { name: "Chatmohar" },
      { name: "Faridpur" },
      { name: "Ishwardi" },
      { name: "Santhia" },
      { name: "Sujanagar" },
    ],
  },
  {
    name: "Sirajganj",
    upazilas: [
      { name: "Sirajganj Sadar" },
      { name: "Belkuchi" },
      { name: "Chauhali" },
      { name: "Dhangora" },
      { name: "Kamarkhanda" },
      { name: "Kazipur" },
      { name: "Raiganj" },
      { name: "Shahjadpur" },
      { name: "Tarash" },
      { name: "Ullapara" },
    ],
  },

  // ── Khulna Division ────────────────────────────────────────────────────
  {
    name: "Khulna",
    upazilas: [
      { name: "Khulna Sadar" },
      { name: "Batiaghata" },
      { name: "Dacope" },
      { name: "Dumuria" },
      { name: "Dighalia" },
      { name: "Koyra" },
      { name: "Paikgachha" },
      { name: "Phultala" },
      { name: "Rupsa" },
      { name: "Terokhada" },
    ],
  },
  {
    name: "Bagerhat",
    upazilas: [
      { name: "Bagerhat Sadar" },
      { name: "Chitalmari" },
      { name: "Fakirahat" },
      { name: "Kachua" },
      { name: "Mollahat" },
      { name: "Mongla" },
      { name: "Morrelganj" },
      { name: "Rampal" },
      { name: "Sarankhola" },
    ],
  },
  {
    name: "Chuadanga",
    upazilas: [
      { name: "Chuadanga Sadar" },
      { name: "Alamdanga" },
      { name: "Damurhuda" },
      { name: "Jibannagar" },
    ],
  },
  {
    name: "Jashore",
    upazilas: [
      { name: "Jashore Sadar" },
      { name: "Abhaynagar" },
      { name: "Bagherpara" },
      { name: "Chaugachha" },
      { name: "Jhikargachha" },
      { name: "Keshabpur" },
      { name: "Manirampur" },
      { name: "Sharsha" },
    ],
  },
  {
    name: "Jhenaidah",
    upazilas: [
      { name: "Jhenaidah Sadar" },
      { name: "Harinakunda" },
      { name: "Kaliganj" },
      { name: "Kotchandpur" },
      { name: "Maheshpur" },
      { name: "Naldanga" },
      { name: "Sailkupa" },
    ],
  },
  {
    name: "Kushtia",
    upazilas: [
      { name: "Kushtia Sadar" },
      { name: "Bheramara" },
      { name: "Daulatpur" },
      { name: "Khoksa" },
      { name: "Kumarkhali" },
      { name: "Mirpur" },
    ],
  },
  {
    name: "Magura",
    upazilas: [
      { name: "Magura Sadar" },
      { name: "Mohammadpur" },
      { name: "Shalikha" },
      { name: "Sreepur" },
    ],
  },
  {
    name: "Meherpur",
    upazilas: [
      { name: "Meherpur Sadar" },
      { name: "Gangni" },
      { name: "Mujibnagar" },
    ],
  },
  {
    name: "Narail",
    upazilas: [
      { name: "Narail Sadar" },
      { name: "Arial" },
      { name: "Kalia" },
      { name: "Lohagara" },
    ],
  },
  {
    name: "Satkhira",
    upazilas: [
      { name: "Satkhira Sadar" },
      { name: "Assasuni" },
      { name: "Debhata" },
      { name: "Kalaroa" },
      { name: "Kaliganj" },
      { name: "Shyamnagar" },
      { name: "Tala" },
    ],
  },

  // ── Barishal Division ──────────────────────────────────────────────────
  {
    name: "Barishal",
    upazilas: [
      { name: "Barishal Sadar" },
      { name: "Agailjhara" },
      { name: "Babuganj" },
      { name: "Bakerganj" },
      { name: "Banaripara" },
      { name: "Gournadi" },
      { name: "Hijla" },
      { name: "Mehendiganj" },
      { name: "Muladi" },
      { name: "Uzirpur" },
    ],
  },
  {
    name: "Barguna",
    upazilas: [
      { name: "Barguna Sadar" },
      { name: "Amtali" },
      { name: "Bamna" },
      { name: "Betagi" },
      { name: "Patharghata" },
      { name: "Taltali" },
    ],
  },
  {
    name: "Bhola",
    upazilas: [
      { name: "Bhola Sadar" },
      { name: "Burhanuddin" },
      { name: "Char Fasson" },
      { name: "Daulatkhan" },
      { name: "Lalmohan" },
      { name: "Manpura" },
      { name: "Tazumuddin" },
    ],
  },
  {
    name: "Jhalokati",
    upazilas: [
      { name: "Jhalokati Sadar" },
      { name: "Kathalia" },
      { name: "Nalchity" },
      { name: "Rajapur" },
    ],
  },
  {
    name: "Patuakhali",
    upazilas: [
      { name: "Patuakhali Sadar" },
      { name: "Bauphal" },
      { name: "Dashmina" },
      { name: "Dumki" },
      { name: "Galachipa" },
      { name: "Kalapara" },
      { name: "Mirzaganj" },
      { name: "Rangabali" },
    ],
  },
  {
    name: "Pirojpur",
    upazilas: [
      { name: "Pirojpur Sadar" },
      { name: "Bhandaria" },
      { name: "Indurkani" },
      { name: "Kawkhali" },
      { name: "Mathbaria" },
      { name: "Nazirpur" },
      { name: "Nesarabad" },
    ],
  },

  // ── Sylhet Division ────────────────────────────────────────────────────
  {
    name: "Sylhet",
    upazilas: [
      { name: "Sylhet Sadar" },
      { name: "Balaganj" },
      { name: "Beanibazar" },
      { name: "Bishwanath" },
      { name: "Companiganj" },
      { name: "Fenchuganj" },
      { name: "Gowainghat" },
      { name: "Jaintiapur" },
      { name: "Kanaighat" },
      { name: "Osmani Nagar" },
      { name: "South Surma" },
      { name: "Zakiganj" },
    ],
  },
  {
    name: "Habiganj",
    upazilas: [
      { name: "Habiganj Sadar" },
      { name: "Ajmiriganj" },
      { name: "Bahubal" },
      { name: "Baniachong" },
      { name: "Chunarughat" },
      { name: "Lakhai" },
      { name: "Madhabpur" },
      { name: "Nabiganj" },
      { name: "Shaistaganj" },
    ],
  },
  {
    name: "Moulvibazar",
    upazilas: [
      { name: "Moulvibazar Sadar" },
      { name: "Barlekha" },
      { name: "Juri" },
      { name: "Kamalganj" },
      { name: "Kulaura" },
      { name: "Rajnagar" },
      { name: "Sreemangal" },
    ],
  },
  {
    name: "Sunamganj",
    upazilas: [
      { name: "Sunamganj Sadar" },
      { name: "Bishwamvarpur" },
      { name: "Chhatak" },
      { name: "Derai" },
      { name: "Dharampasha" },
      { name: "Dowarabazar" },
      { name: "Jagannathpur" },
      { name: "Jamalganj" },
      { name: "Sullah" },
      { name: "Tahirpur" },
    ],
  },

  // ── Rangpur Division ───────────────────────────────────────────────────
  {
    name: "Rangpur",
    upazilas: [
      { name: "Rangpur Sadar" },
      { name: "Badarganj" },
      { name: "Gangachhara" },
      { name: "Kaunia" },
      { name: "Mithapukur" },
      { name: "Pirgachha" },
      { name: "Pirganj" },
      { name: "Taraganj" },
    ],
  },
  {
    name: "Dinajpur",
    upazilas: [
      { name: "Dinajpur Sadar" },
      { name: "Birampur" },
      { name: "Birganj" },
      { name: "Bochaganj" },
      { name: "Chirirbandar" },
      { name: "Fulbari" },
      { name: "Ghoraghat" },
      { name: "Hakimpur" },
      { name: "Kaharole" },
      { name: "Khansama" },
      { name: "Nawabganj" },
      { name: "Parbatipur" },
    ],
  },
  {
    name: "Gaibandha",
    upazilas: [
      { name: "Gaibandha Sadar" },
      { name: "Fulchhari" },
      { name: "Gobindaganj" },
      { name: "Palashbari" },
      { name: "Sadullapur" },
      { name: "Saghata" },
      { name: "Sundarganj" },
    ],
  },
  {
    name: "Kurigram",
    upazilas: [
      { name: "Kurigram Sadar" },
      { name: "Bhurungamari" },
      { name: "Char Rajibpur" },
      { name: "Chilmari" },
      { name: "Phulbari" },
      { name: "Nageshwari" },
      { name: "Rajarhat" },
      { name: "Raomari" },
      { name: "Ulipur" },
    ],
  },
  {
    name: "Lalmonirhat",
    upazilas: [
      { name: "Lalmonirhat Sadar" },
      { name: "Aditmari" },
      { name: "Hatibandha" },
      { name: "Kaliganj" },
      { name: "Patgram" },
    ],
  },
  {
    name: "Nilphamari",
    upazilas: [
      { name: "Nilphamari Sadar" },
      { name: "Dimla" },
      { name: "Domar" },
      { name: "Jaldhaka" },
      { name: "Kishoreganj" },
      { name: "Saidpur" },
    ],
  },
  {
    name: "Panchagarh",
    upazilas: [
      { name: "Panchagarh Sadar" },
      { name: "Atwari" },
      { name: "Boda" },
      { name: "Debiganj" },
      { name: "Tetulia" },
    ],
  },
  {
    name: "Thakurgaon",
    upazilas: [
      { name: "Thakurgaon Sadar" },
      { name: "Baliadangi" },
      { name: "Haripur" },
      { name: "Pirganj" },
      { name: "Ranisankail" },
    ],
  },

  // ── Mymensingh Division ────────────────────────────────────────────────
  {
    name: "Mymensingh",
    upazilas: [
      { name: "Mymensingh Sadar" },
      { name: "Bhaluka" },
      { name: "Dhobaura" },
      { name: "Fulbaria" },
      { name: "Gafargaon" },
      { name: "Gauripur" },
      { name: "Haluaghat" },
      { name: "Ishwarganj" },
      { name: "Muktagachha" },
      { name: "Nandail" },
      { name: "Phulpur" },
      { name: "Trishal" },
      { name: "Tara Khail" },
    ],
  },
  {
    name: "Jamalpur",
    upazilas: [
      { name: "Jamalpur Sadar" },
      { name: "Baksiganj" },
      { name: "Dewanganj" },
      { name: "Islampur" },
      { name: "Madarganj" },
      { name: "Melandaha" },
      { name: "Sarishabari" },
    ],
  },
  {
    name: "Netrokona",
    upazilas: [
      { name: "Netrokona Sadar" },
      { name: "Atpara" },
      { name: "Barhatta" },
      { name: "Durgapur" },
      { name: "Khaliajuri" },
      { name: "Kendua" },
      { name: "Madan" },
      { name: "Mohanganj" },
      { name: "Purbadhala" },
    ],
  },
  {
    name: "Sherpur",
    upazilas: [
      { name: "Sherpur Sadar" },
      { name: "Jhenaigati" },
      { name: "Nakla" },
      { name: "Nalitabari" },
      { name: "Sreebardi" },
    ],
  },
];